POST https://user.crowdproj.com/api/get
Content-Type: application/json

{
  "userId": "dfe5a9fc-2a1b-4824-9bc0-276ba1767848"
}

###
POST https://user.crowdproj.com/api/index
Content-Type: application/json

{
  "filter": {
    "dob": "2000-01-01"
  }
}

###
POST https://user.crowdproj.com/api/create
Content-Type: application/json

{
  "fname": "First",
  "mname": "Middle",
  "lname": "Last",
  "dob": "2000-01-01",
  "email": "email@email.email",
  "phone": "+7 999 999 9999"
}

###
POST https://user.crowdproj.com/api/update
Content-Type: application/json

{
  "id": "dfe5a9fc-2a1b-4824-9bc0-276ba1767848",
  "fname": "Ivan",
  "mname": "Ivanovich",
  "lname": "Ivanov",
  "dob": "2000-01-01",
  "email": "email@email.email",
  "phone": "+7 999 999 9999"
}

###
